* Magic Earth (Obtainium Mirror)
:PROPERTIES:
:CUSTOM_ID: magic-earth-obtainium-mirror
:END:
Automated mirror for [[https://www.magicearth.com][Magic Earth (maps)]] Android APKs, verified against the official ROUTE 66 signature.

Designed for use with [[https://obtainium.imranr.dev/][Obtainium]].

New releases are checked for hourly.

** How to use with Obtainium
:PROPERTIES:
:CUSTOM_ID: how-to-use-with-obtainium
:END:
1. Copy this URL: =https://github.com/emacsomancer/Obtainium-friendly-Magic-Earth=
2. Open *Obtainium* and click *Add App*.
3. Paste the above URL.
4. Click *Add*.

It's maybe a bit slow to add the first time.

** Method
:PROPERTIES:
:CUSTOM_ID: method
:END:
Every APK in this repository is just copied from [[https://www.magicearth.com/download][Magic Earth's download page]] and then automatically verified using =apksigner= against the official Magic Earth SHA-256 certificate fingerprint before being published.

*** Misc.
:PROPERTIES:
:CUSTOM_ID: misc
:END:
Some relevant discussions:

- Obtainium discussion [[" Can we add Magic Earth to Complex apps if not already? #2794"][https://github.com/ImranR98/Obtainium/discussions/2794]]   
- and also this earlier discussion, particularly this post which suggest possibly a recipe to add directly from the Magic Earth download page? - https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/331#discussioncomment-15483020
#+begin_src shell
https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.generalmagic.magicearth%22%2C%22url%22%3A%22https%3A%2F%2Fwww.magicearth.com%2Fdownload%22%2C%22author%22%3A%22www.magicearth.com%22%2C%22name%22%3A%22Magic%20Earth%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22arm64%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22matchLinksOutsideATags%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22-(%5C%5C%5C%5Cd.*)-a%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%241%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22Magic%20Earth%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22Magic%20Lane%20International%20BV%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22GPS%20Navigation%2C%20Offline%20Maps%20and%20Crowd-sourced%20Traffic.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D
#+end_src

But I've only seen these after creating this repo, and haven't verified the suggestion.

